# Generated by Django 6.0.4 on 2026-04-27 16:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('intern', 'Intern'), ('team', 'Team'), ('supporter', 'Supporter')], default='supporter', max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('shoe_size', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.PositiveIntegerField(default=0)),
                ('approved', models.PositiveIntegerField(default=0)),
                ('used', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('credit', 'Credit'), ('approve', 'Approve'), ('redeem', 'Redeem')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pilot.pointsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_id', models.CharField(max_length=40, unique=True)),
                ('product_line', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Pre-booked', 'Pre-booked'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pre-booked', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged')], max_length=20)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Received', 'Received'), ('Completed', 'Completed')], default='Requested', max_length=20)),
                ('final_action', models.CharField(blank=True, choices=[('Repair', 'Repair'), ('Reuse', 'Reuse'), ('Recycle', 'Recycle')], max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to=settings.AUTH_USER_MODEL)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='pilot.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolicTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.CharField(max_length=40, unique=True)),
                ('plant_type', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=140)),
                ('status', models.CharField(default='Symbolic Tree Parent', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('days_worn', models.PositiveSmallIntegerField()),
                ('hours_per_day', models.PositiveSmallIntegerField()),
                ('comfort', models.PositiveSmallIntegerField()),
                ('fit', models.PositiveSmallIntegerField()),
                ('sole', models.PositiveSmallIntegerField()),
                ('material', models.PositiveSmallIntegerField()),
                ('stitching', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='reviews/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week'), name='unique_review_per_user_week')],
            },
        ),
    ]
