# Generated by Django 6.0.4 on 2026-04-27 18:56

from django.db import migrations, models


def mark_seeded_demo_users(apps, schema_editor):
    PilotUser = apps.get_model("pilot", "PilotUser")
    PilotUser.objects.filter(
        is_staff=False,
        email__startswith="pilot",
        email__endswith="@ekokintsugi.com",
    ).update(is_demo_user=True)


def unmark_seeded_demo_users(apps, schema_editor):
    PilotUser = apps.get_model("pilot", "PilotUser")
    PilotUser.objects.filter(
        is_staff=False,
        email__startswith="pilot",
        email__endswith="@ekokintsugi.com",
    ).update(is_demo_user=False)


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotuser',
            name='is_demo_user',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_seeded_demo_users, unmark_seeded_demo_users),
    ]
